#%RAML 1.0 SecurityScheme
#=======================================================================
# Common API Elements
# SecuritySchemes/standard-security-scheme.raml
# Date   : September 09, 2019
# Author : NITISH
# Rev    : 1
#=======================================================================
type: Basic Authentication
description: Use application client_id and secret assigned by API administrator.