#%RAML 1.0 NamedExample
#=======================================================================
# Common API Elements
# NamedExamples/get-ping-response.raml
# Date   : September 09, 2019
# Author : NITISH
# Rev    : 1
#=======================================================================
GetPingResponseExample:
  status: "200"
  message: Alive
