#%RAML 1.0 Library
#=======================================================================
# Common API Elements
# standard-security.raml
# Date   : September 09, 2019
# Author : NITISH
# Rev    : 1

#=======================================================================
usage: Standard Security Schemes

securitySchemes: 
  basic: !include SecuritySchemas/standard-security-schema.raml