#%RAML 1.0 Trait
usage: Client queryparams Required Trait
queryParameters:
  startDate:
    description: Start date
    type: date-only
    example: 2019-10-11
  endDate:
    description: End date
    type: date-only
    example: 2010-12-12
  userEntry9:
    description: User entry
    type: string
    example: sy