#%RAML 1.0 Trait
#=======================================================================
# Common API Elements
# Traits/standard-accept-required-trait.raml
# Date   : September 09, 2019
# Author : NITISH
# Rev    : 1
#=======================================================================
usage: Accept Required Trait
headers:
  Accept:
    type: string
    example: application/json
