#%RAML 1.0 Trait
#=======================================================================
# Common API Elements
# Traits/standard-client-authorization-required-trait.raml
# Date   : September 09, 2019
# Author : NITISH
# Rev    : 1
#=======================================================================
usage: Client Authorization Required Trait
    
headers:
  Authorization:
    type: string
    example: Basic YjFjNGRlMmM4YTQ4NDk5M2IwNTc5ZDg1YzU0ZjRjNDM6ZEIxNUY1MWY0MjZBNEExNDkwOWQzMGJEQWFhMURFMmQ=
  authorization:
    type: string
    example: Basic YjFjNGRlMmM4YTQ4NDk5M2IwNTc5ZDg1YzU0ZjRjNDM6ZEIxNUY1MWY0MjZBNEExNDkwOWQzMGJEQWFhMURFMmQ=     
