#%RAML 1.0 Trait
#=======================================================================
# Common API Elements
# Traits/standard-content-type-required-trait.raml
# Date   : September 09, 2019
# Author : NITISH
# Rev    : 1
#=======================================================================
usage: Content Type Required Trait
headers: 
  Content-Type:
    type: string
    example: application/json
